version: 0.0
os: linux
files:
  - source: /
    destination: /opt/sw/

permissions:
  - object: /opt/sw/
    pattern: "*"
    mode: 777
    
hooks:

  AfterInstall:
    - location: runAdminPortal1.sh
      timeout: 1000
      runas: root


