version: 0.0
os: linux
files:
  - source: /
    destination: /opt/capstone/

permissions:
  - object: /opt/capstone/
    pattern: "**"
    mode: 4777
    
hooks:
  AfterInstall:
    - location: runAdminPortal1.sh
      timeout: 300
      runas: root


