version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/managemylearning-admin-portal-0.0.1-SNAPSHOT.jar
  discard-paths: yes
  name: managemylearning-admin-portal-0.0.1-SNAPSHOT.zip